# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  noClasses = false

[markup]
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1